### ISSUE TITLE
Crash when selecting subtitles

### ISSUE THREAD

**Issue by shaarkys** [mx3L/subssupport#3]
**Vu+ SOLO2**
**enigma2-plugin-extensions-subssupport_1.5.3_20150714_all.ipk**

Screen <class 'Plugins.Extensions.SubsSupport.subtitles.SubsChooser'>((<Components.config.ConfigSubsection object at 0x2a36d70>, '/media/hdd/movie/++FILMY++', True, False, True), {}): <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/mytest.py", line 239, in create
    return screen(self, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/Plugins/Extensions/SubsSupport/subtitles.py", line 2418, in __init__
    self["file_list"] = SubFileList(defaultDir)
  File "/usr/lib/enigma2/python/Plugins/Extensions/SubsSupport/subtitles.py", line 2197, in __init__
    FileList.__init__(self, defaultDir, matchingPattern="(?i)^.*\." + '(' + '|'.join(ext[1:] for ext in extensions) + ')', useServiceRef=False)
  File "/usr/lib/enigma2/python/Plugins/Extensions/SubsSupport/compat.py", line 92, in __init__
    font = skin.fonts.get("FileList", ("Regular", 18, 23))
AttributeError: 'module' object has no attribute 'fonts'
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 46, in action
    res = self.actions[action]()
  File "/usr/lib/enigma2/python/Plugins/Extensions/SubsSupport/subtitles.py", line 1889, in ok
    self.session.openWithCallback(self.subsChooserCB, SubsChooser, self.infobar.subsSettings, self.subdir, self.embeddedSupport, False, True)
  File "/usr/lib/enigma2/python/mytest.py", line 302, in openWithCallback
    dlg = self.open(screen, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/mytest.py", line 313, in open
    dlg.isTmp = True
AttributeError: 'NoneType' object has no attribute 'isTmp'
(PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap instance at 0x2a518f0>>,('SetupActions', 'ok')) failed)
]]>

**Comment by mx3L** [comment]
please test this version:
http://dl.bintray.com/mx3l/generic/:enigma2-plugin-extensions-subssupport_1.5.4_20150824_all.ipk

**Comment by shaarkys** [comment]
Working, thank you so such a quick fix ! ;-)
