### ISSUE TITLE
crash on OpenSubtitlesSuggestions

### ISSUE THREAD

**Issue by fairbird** [mx3L/subssupport#60]
> Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/SubsSupport/e2_utils.py", line 76, in selectionChanged
    return ConfigList.selectionChanged(self)
  File "/usr/lib/enigma2/python/Components/ConfigList.py", line 72, in selectionChanged
  File "/usr/lib/enigma2/python/Plugins/Extensions/SubsSupport/subtitles.py", line 3426, in onSelect
    self.getSuggestions()
  File "/usr/lib/enigma2/python/Plugins/Extensions/SubsSupport/subtitles.py", line 3533, in getSuggestions
    self.__suggestions = self.suggestionsClass().getSuggestions(self.value, self.propagateSuggestions, self.gotSuggestionsError)
  File "/usr/lib/enigma2/python/Plugins/Extensions/SubsSupport/subtitles.py", line 3245, in getSuggestions
    d = self._getSuggestions(queryString)
  File "/usr/lib/enigma2/python/Plugins/Extensions/SubsSupport/subtitles.py", line 3269, in _getSuggestions
    return client.getPage(query, timeout=6)
  File "/usr/lib/python2.7/site-packages/twisted/python/deprecate.py", line 301, in deprecatedFunction
  File "/usr/lib/python2.7/site-packages/twisted/web/client.py", line 795, in getPage
  File "/usr/lib/python2.7/site-packages/twisted/web/client.py", line 742, in _makeGetterFactory
  File "/usr/lib/python2.7/site-packages/twisted/web/_newclient.py", line 648, in _ensureValidURI
ValueError: Invalid URI 'http://www.opensubtitles.org/libs/suggest.php?format=json2&SubLanguageID=null&MovieName=Marie Antoinette'
< 19430.166> [ePyObject] (CallObject(<bound method MyConfigList.selectionChanged of <Plugins.Extensions.SubsSupport.e2_utils.MyConfigList object at 0xaec95410>>,()) failed)

**Comment by athoik** [comment]
Same issue as here: https://github.com/Sirius0103/enigma2-plugins/pull/2

So adding `quote` on MovieName will fix issue.

**Comment by fairbird** [comment]
Thank you my bro ..
I will try it if work fine I will push bull request ..
